ktor:
  application:
    modules:
      - dev.surovtsev.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  url: jdbc:postgresql://${POSTGRES_SERVER:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:train_mate_ai_data}
  user: ${POSTGRES_USERNAME:postgres}
  password: ${POSTGRES_PASSWORD:postgres}
